### ISSUE TITLE
Complete D4.1 section

### ISSUE THREAD

**Issue by CFGrote** [eucall-software/simex_docs#1]
- Introduction (science case, motivation, background)
- Which material, diagnostic (SAXS?)
- Fix experimental conditions based on what's available at HED

Timeline: to be completed by 2016-06-13 12 noon

**Comment by ax3l** [comment]
CC @HighIander

**Comment by bussmann** [comment]
I'll be on it by tomorrow. Have to write smth else today.

**Comment by CFGrote** [comment]
ok, great.

On 06/13/2016 10:29 AM, Michael Bussmann wrote:
> I'll be on it by tomorrow. Have to write smth else today.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/eucall-software/simex_docs/issues/1#issuecomment-225518541>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AOwoR2iVejjdfThSAYcYiRwIO5gCyAh-ks5qLRUBgaJpZM4Ix3vV>.
> 

-- 
--
Carsten Fortmann-Grote
Scientist
European XFEL GmbH

Mail: carsten.grote@xfel.eu
Phone: +49 (0)40 8998 5603

**Comment by CFGrote** [comment]
Still missing is the description of the scattering calculation. is this part of picongpu or a separate tool?

**Comment by bussmann** [comment]
Separate. Description is coming.
