### ISSUE TITLE
Add graphics, datasets, dataformat descrition to M4.3

### ISSUE THREAD

**Issue by CFGrote** [eucall-software/simex_docs#11]
@richardbriggs , your section in M4.3 looks a bit shallow compared to the others. Do you want to add any material (figures, data, etc)?
[M4.3.pdf](https://github.com/eucall-software/simex_docs/files/1299019/M4.3.pdf)

**Comment by CFGrote** [comment]
@richardbriggs: That being said, I have not yet included your material on the rad-hydro and FEFF calculations.

**Comment by richardbriggs** [comment]
I can add the hydro and FEFF aspects and can create some more useful figures from the radhydro analysis. I'm having trouble typesetting the M4.3.tex document though.

**Comment by CFGrote** [comment]
what's the matter with the tex file?

**Comment by richardbriggs** [comment]
I’m using TeXshop on mac and when I hit typeset nothing happens.

On 13 September 2017 at 14:54:17, Carsten Fortmann-Grote (notifications@github.com) wrote:

what's the matter with the tex file?

**Comment by CFGrote** [comment]
try to typeset Milestones/M4.3/contributions/WDM/Task 4.2.2.10.tex

carsten

On Wed, Sep 13, 2017 at 12:55:52PM +0000, Richard Briggs wrote:
> I’m using TeXshop on mac and when I hit typeset nothing happens.
>
> On 13 September 2017 at 14:54:17, Carsten Fortmann-Grote (notifications@github.com) wrote:
>
> what's the matter with the tex file?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/eucall-software/simex_docs/issues/11#issuecomment-329158632

--
Dr. Carsten Fortmann-Grote
Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
European XFEL GmbH
Holzkoppel 4
22869 Schenefeld
Germany

Phone: +49 (0)40 8998-5603
Fax:   +49 (0)40 8998-1905
Email: carsten.grote@xfel.eu
Web: www.xfel.eu

Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger

Registered as European X-Ray Free-Electron Laser Facility GmbH
at Amtsgericht Hamburg, HRB 111165

**Comment by richardbriggs** [comment]
The file isn’t on GitHub yet, only the two docx files.
On 13 September 2017 at 15:02:48, Carsten Fortmann-Grote (notifications@github.com) wrote:

try to typeset Milestones/M4.3/contributions/WDM/Task 4.2.2.10.tex

carsten

On Wed, Sep 13, 2017 at 12:55:52PM +0000, Richard Briggs wrote:
> I’m using TeXshop on mac and when I hit typeset nothing happens.
>
> On 13 September 2017 at 14:54:17, Carsten Fortmann-Grote (notifications@github.com) wrote:
>
> what's the matter with the tex file?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/eucall-software/simex_docs/issues/11#issuecomment-329158632

--
Dr. Carsten Fortmann-Grote
Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
European XFEL GmbH
Holzkoppel 4
22869 Schenefeld
Germany

Phone: +49 (0)40 8998-5603
Fax: +49 (0)40 8998-1905
Email: carsten.grote@xfel.eu
Web: www.xfel.eu

Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger

Registered as European X-Ray Free-Electron Laser Facility GmbH
at Amtsgericht Hamburg, HRB 111165

**Comment by CFGrote** [comment]
sorry. just pushed the missing files.

c.

On Wed, Sep 13, 2017 at 01:23:33PM +0000, Richard Briggs wrote:
> The file isn’t on GitHub yet, only the two docx files.
> On 13 September 2017 at 15:02:48, Carsten Fortmann-Grote (notifications@github.com) wrote:
>
> try to typeset Milestones/M4.3/contributions/WDM/Task 4.2.2.10.tex
>
> carsten
>
> On Wed, Sep 13, 2017 at 12:55:52PM +0000, Richard Briggs wrote:
> > I’m using TeXshop on mac and when I hit typeset nothing happens.
> >
> > On 13 September 2017 at 14:54:17, Carsten Fortmann-Grote (notifications@github.com) wrote:
> >
> > what's the matter with the tex file?
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
> >
> >
> > --
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/eucall-software/simex_docs/issues/11#issuecomment-329158632
>
> --
> Dr. Carsten Fortmann-Grote
> Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
> European XFEL GmbH
> Holzkoppel 4
> 22869 Schenefeld
> Germany
>
> Phone: +49 (0)40 8998-5603
> Fax: +49 (0)40 8998-1905
> Email: carsten.grote@xfel.eu
> Web: www.xfel.eu
>
> Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger
>
> Registered as European X-Ray Free-Electron Laser Facility GmbH
> at Amtsgericht Hamburg, HRB 111165
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/eucall-software/simex_docs/issues/11#issuecomment-329166351

--
Dr. Carsten Fortmann-Grote
Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
European XFEL GmbH
Holzkoppel 4
22869 Schenefeld
Germany

Phone: +49 (0)40 8998-5603
Fax:   +49 (0)40 8998-1905
Email: carsten.grote@xfel.eu
Web: www.xfel.eu

Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger

Registered as European X-Ray Free-Electron Laser Facility GmbH
at Amtsgericht Hamburg, HRB 111165

**Comment by richardbriggs** [comment]
I’ve added the figures symbolic link and two packages were missing in task 4.2.2.10 tex file but it’s working now thanks. Let me add what i’ve done to this file and i’ll let you know once i’ve pushed.

Cheers,
R
On 13 September 2017 at 15:41:33, Carsten Fortmann-Grote (notifications@github.com) wrote:

sorry. just pushed the missing files.

c.

On Wed, Sep 13, 2017 at 01:23:33PM +0000, Richard Briggs wrote:
> The file isn’t on GitHub yet, only the two docx files.
> On 13 September 2017 at 15:02:48, Carsten Fortmann-Grote (notifications@github.com) wrote:
>
> try to typeset Milestones/M4.3/contributions/WDM/Task 4.2.2.10.tex
>
> carsten
>
> On Wed, Sep 13, 2017 at 12:55:52PM +0000, Richard Briggs wrote:
> > I’m using TeXshop on mac and when I hit typeset nothing happens.
> >
> > On 13 September 2017 at 14:54:17, Carsten Fortmann-Grote (notifications@github.com) wrote:
> >
> > what's the matter with the tex file?
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
> >
> >
> > --
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/eucall-software/simex_docs/issues/11#issuecomment-329158632
>
> --
> Dr. Carsten Fortmann-Grote
> Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
> European XFEL GmbH
> Holzkoppel 4
> 22869 Schenefeld
> Germany
>
> Phone: +49 (0)40 8998-5603
> Fax: +49 (0)40 8998-1905
> Email: carsten.grote@xfel.eu
> Web: www.xfel.eu
>
> Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger
>
> Registered as European X-Ray Free-Electron Laser Facility GmbH
> at Amtsgericht Hamburg, HRB 111165
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/eucall-software/simex_docs/issues/11#issuecomment-329166351

--
Dr. Carsten Fortmann-Grote
Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
European XFEL GmbH
Holzkoppel 4
22869 Schenefeld
Germany

Phone: +49 (0)40 8998-5603
Fax: +49 (0)40 8998-1905
Email: carsten.grote@xfel.eu
Web: www.xfel.eu

Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger

Registered as European X-Ray Free-Electron Laser Facility GmbH
at Amtsgericht Hamburg, HRB 111165

**Comment by CFGrote** [comment]
ok, much appreciated.

c.

On Wed, Sep 13, 2017 at 07:03:13AM -0700, Richard Briggs wrote:
> I’ve added the figures symbolic link and two packages were missing in task 4.2.2.10 tex file but it’s working now thanks. Let me add what i’ve done to this file and i’ll let you know once i’ve pushed.
>
> Cheers,
> R
> On 13 September 2017 at 15:41:33, Carsten Fortmann-Grote (notifications@github.com) wrote:
>
> sorry. just pushed the missing files.
>
> c.
>
> On Wed, Sep 13, 2017 at 01:23:33PM +0000, Richard Briggs wrote:
> > The file isn’t on GitHub yet, only the two docx files.
> > On 13 September 2017 at 15:02:48, Carsten Fortmann-Grote (notifications@github.com) wrote:
> >
> > try to typeset Milestones/M4.3/contributions/WDM/Task 4.2.2.10.tex
> >
> > carsten
> >
> > On Wed, Sep 13, 2017 at 12:55:52PM +0000, Richard Briggs wrote:
> > > I’m using TeXshop on mac and when I hit typeset nothing happens.
> > >
> > > On 13 September 2017 at 14:54:17, Carsten Fortmann-Grote (notifications@github.com) wrote:
> > >
> > > what's the matter with the tex file?
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub, or mute the thread.
> > >
> > >
> > >
> > > --
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/eucall-software/simex_docs/issues/11#issuecomment-329158632
> >
> > --
> > Dr. Carsten Fortmann-Grote
> > Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
> > European XFEL GmbH
> > Holzkoppel 4
> > 22869 Schenefeld
> > Germany
> >
> > Phone: +49 (0)40 8998-5603
> > Fax: +49 (0)40 8998-1905
> > Email: carsten.grote@xfel.eu
> > Web: www.xfel.eu
> >
> > Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger
> >
> > Registered as European X-Ray Free-Electron Laser Facility GmbH
> > at Amtsgericht Hamburg, HRB 111165
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
> >
> >
> > --
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/eucall-software/simex_docs/issues/11#issuecomment-329166351
>
> --
> Dr. Carsten Fortmann-Grote
> Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
> European XFEL GmbH
> Holzkoppel 4
> 22869 Schenefeld
> Germany
>
> Phone: +49 (0)40 8998-5603
> Fax: +49 (0)40 8998-1905
> Email: carsten.grote@xfel.eu
> Web: www.xfel.eu
>
> Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger
>
> Registered as European X-Ray Free-Electron Laser Facility GmbH
> at Amtsgericht Hamburg, HRB 111165
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/eucall-software/simex_docs/issues/11#issuecomment-329177807

--
Dr. Carsten Fortmann-Grote
Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
European XFEL GmbH
Holzkoppel 4
22869 Schenefeld
Germany

Phone: +49 (0)40 8998-5603
Fax:   +49 (0)40 8998-1905
Email: carsten.grote@xfel.eu
Web: www.xfel.eu

Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger

Registered as European X-Ray Free-Electron Laser Facility GmbH
at Amtsgericht Hamburg, HRB 111165

**Comment by richardbriggs** [comment]
OK, so i THINK that I’ve pushed my changes. It’s only taken about 2 years to get the hang of GitHub properly…hopefully.

I’ve adjusted the tex slightly in M4.3.tex and then added some text / figure and edited the xafs.tex file. (There was a weird bug with using underscore in \href that I couldn’t fix. the text is in bold). 

Let me know if that worked and if you think it needs more work. 

On 13 September 2017 at 16:07:45, Carsten Fortmann-Grote (notifications@github.com) wrote:

ok, much appreciated.

c.

On Wed, Sep 13, 2017 at 07:03:13AM -0700, Richard Briggs wrote:
> I’ve added the figures symbolic link and two packages were missing in task 4.2.2.10 tex file but it’s working now thanks. Let me add what i’ve done to this file and i’ll let you know once i’ve pushed.
>
> Cheers,
> R
> On 13 September 2017 at 15:41:33, Carsten Fortmann-Grote (notifications@github.com) wrote:
>
> sorry. just pushed the missing files.
>
> c.
>
> On Wed, Sep 13, 2017 at 01:23:33PM +0000, Richard Briggs wrote:
> > The file isn’t on GitHub yet, only the two docx files.
> > On 13 September 2017 at 15:02:48, Carsten Fortmann-Grote (notifications@github.com) wrote:
> >
> > try to typeset Milestones/M4.3/contributions/WDM/Task 4.2.2.10.tex
> >
> > carsten
> >
> > On Wed, Sep 13, 2017 at 12:55:52PM +0000, Richard Briggs wrote:
> > > I’m using TeXshop on mac and when I hit typeset nothing happens.
> > >
> > > On 13 September 2017 at 14:54:17, Carsten Fortmann-Grote (notifications@github.com) wrote:
> > >
> > > what's the matter with the tex file?
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub, or mute the thread.
> > >
> > >
> > >
> > > --
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/eucall-software/simex_docs/issues/11#issuecomment-329158632
> >
> > --
> > Dr. Carsten Fortmann-Grote
> > Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
> > European XFEL GmbH
> > Holzkoppel 4
> > 22869 Schenefeld
> > Germany
> >
> > Phone: +49 (0)40 8998-5603
> > Fax: +49 (0)40 8998-1905
> > Email: carsten.grote@xfel.eu
> > Web: www.xfel.eu
> >
> > Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger
> >
> > Registered as European X-Ray Free-Electron Laser Facility GmbH
> > at Amtsgericht Hamburg, HRB 111165
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
> >
> >
> > --
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/eucall-software/simex_docs/issues/11#issuecomment-329166351
>
> --
> Dr. Carsten Fortmann-Grote
> Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
> European XFEL GmbH
> Holzkoppel 4
> 22869 Schenefeld
> Germany
>
> Phone: +49 (0)40 8998-5603
> Fax: +49 (0)40 8998-1905
> Email: carsten.grote@xfel.eu
> Web: www.xfel.eu
>
> Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger
>
> Registered as European X-Ray Free-Electron Laser Facility GmbH
> at Amtsgericht Hamburg, HRB 111165
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/eucall-software/simex_docs/issues/11#issuecomment-329177807

--
Dr. Carsten Fortmann-Grote
Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
European XFEL GmbH
Holzkoppel 4
22869 Schenefeld
Germany

Phone: +49 (0)40 8998-5603
Fax: +49 (0)40 8998-1905
Email: carsten.grote@xfel.eu
Web: www.xfel.eu

Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger

Registered as European X-Ray Free-Electron Laser Facility GmbH
at Amtsgericht Hamburg, HRB 111165

**Comment by CFGrote** [comment]
hi richard,
ok, thanks again. i won't find time to look into this until tomorrow
evening.

carsten

On Wed, Sep 13, 2017 at 07:38:04AM -0700, Richard Briggs wrote:
> OK, so i THINK that I’ve pushed my changes. It’s only taken about 2 years to get the hang of GitHub properly…hopefully.
>
> I’ve adjusted the tex slightly in M4.3.tex and then added some text / figure and edited the xafs.tex file. (There was a weird bug with using underscore in \href that I couldn’t fix. the text is in bold). 
>
> Let me know if that worked and if you think it needs more work. 
>
> On 13 September 2017 at 16:07:45, Carsten Fortmann-Grote (notifications@github.com) wrote:
>
> ok, much appreciated.
>
> c.
>
> On Wed, Sep 13, 2017 at 07:03:13AM -0700, Richard Briggs wrote:
> > I’ve added the figures symbolic link and two packages were missing in task 4.2.2.10 tex file but it’s working now thanks. Let me add what i’ve done to this file and i’ll let you know once i’ve pushed.
> >
> > Cheers,
> > R
> > On 13 September 2017 at 15:41:33, Carsten Fortmann-Grote (notifications@github.com) wrote:
> >
> > sorry. just pushed the missing files.
> >
> > c.
> >
> > On Wed, Sep 13, 2017 at 01:23:33PM +0000, Richard Briggs wrote:
> > > The file isn’t on GitHub yet, only the two docx files.
> > > On 13 September 2017 at 15:02:48, Carsten Fortmann-Grote (notifications@github.com) wrote:
> > >
> > > try to typeset Milestones/M4.3/contributions/WDM/Task 4.2.2.10.tex
> > >
> > > carsten
> > >
> > > On Wed, Sep 13, 2017 at 12:55:52PM +0000, Richard Briggs wrote:
> > > > I’m using TeXshop on mac and when I hit typeset nothing happens.
> > > >
> > > > On 13 September 2017 at 14:54:17, Carsten Fortmann-Grote (notifications@github.com) wrote:
> > > >
> > > > what's the matter with the tex file?
> > > >
> > > > —
> > > > You are receiving this because you were mentioned.
> > > > Reply to this email directly, view it on GitHub, or mute the thread.
> > > >
> > > >
> > > >
> > > > --
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/eucall-software/simex_docs/issues/11#issuecomment-329158632
> > >
> > > --
> > > Dr. Carsten Fortmann-Grote
> > > Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
> > > European XFEL GmbH
> > > Holzkoppel 4
> > > 22869 Schenefeld
> > > Germany
> > >
> > > Phone: +49 (0)40 8998-5603
> > > Fax: +49 (0)40 8998-1905
> > > Email: carsten.grote@xfel.eu
> > > Web: www.xfel.eu
> > >
> > > Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger
> > >
> > > Registered as European X-Ray Free-Electron Laser Facility GmbH
> > > at Amtsgericht Hamburg, HRB 111165
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly, view it on GitHub, or mute the thread.
> > >
> > >
> > >
> > > --
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/eucall-software/simex_docs/issues/11#issuecomment-329166351
> >
> > --
> > Dr. Carsten Fortmann-Grote
> > Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
> > European XFEL GmbH
> > Holzkoppel 4
> > 22869 Schenefeld
> > Germany
> >
> > Phone: +49 (0)40 8998-5603
> > Fax: +49 (0)40 8998-1905
> > Email: carsten.grote@xfel.eu
> > Web: www.xfel.eu
> >
> > Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger
> >
> > Registered as European X-Ray Free-Electron Laser Facility GmbH
> > at Amtsgericht Hamburg, HRB 111165
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> >
> >
> >
> > --
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub:
> > https://github.com/eucall-software/simex_docs/issues/11#issuecomment-329177807
>
> --
> Dr. Carsten Fortmann-Grote
> Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
> European XFEL GmbH
> Holzkoppel 4
> 22869 Schenefeld
> Germany
>
> Phone: +49 (0)40 8998-5603
> Fax: +49 (0)40 8998-1905
> Email: carsten.grote@xfel.eu
> Web: www.xfel.eu
>
> Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger
>
> Registered as European X-Ray Free-Electron Laser Facility GmbH
> at Amtsgericht Hamburg, HRB 111165
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/eucall-software/simex_docs/issues/11#issuecomment-329188588

--
Dr. Carsten Fortmann-Grote
Scientist for Scientific Simulations / Wissenschaftler fuer wissenschaftliche Simulationen
European XFEL GmbH
Holzkoppel 4
22869 Schenefeld
Germany

Phone: +49 (0)40 8998-5603
Fax:   +49 (0)40 8998-1905
Email: carsten.grote@xfel.eu
Web: www.xfel.eu

Managing Directors: Prof. Dr. Robert Feidenhans'l, Dr. Claudia Burger

Registered as European X-Ray Free-Electron Laser Facility GmbH
at Amtsgericht Hamburg, HRB 111165
